# Valkey w Admin GUI

services:      

  # Valkey db container
  valkey-db:
    networks:
      - caddynet
    image: valkey/valkey:9.0-alpine
    container_name: valkey-server
    command: >
      valkey-server --requirepass ${VALKEY_PASSWORD} --appendonly yes
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /opt/1panel/docker/compose/valkey/valkey_data:/data
      
  # GUI container
  valkey-admin:
    networks:
      - caddynet
    image: valkey/valkey-admin:1.1.1
    container_name: valkey-admin-web
    restart: unless-stopped
    ports:
      - "8655:8080"
    environment:
      - DEPLOYMENT_MODE=Web
      - VALKEY_HOST=valkey-db
      - VALKEY_PORT=6379
      - VALKEY_USERNAME=${VALKEY_USERNAME}
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
    depends_on:
      - valkey-db

#########
networks:
  caddynet:
    external: true
