# Valkey w Admin GUI

services:

  # network
  networks:
    caddynet:
      external: true

  # Valkey db container
  valkey:
    networks:
      - caddynet
    image: valkey/valkey:9.0-alpine
    container_name: valkey-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /opt/1panel/docker/compose/valkey/valkey_data:/data
      
  # GUI container
  valkey-admin:
    image: valkey/valkey-admin:1.1.1
    container_name: valkey-admin-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_MODE=Web
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - VALKEY_USERNAME=default
      - VALKEY_PASSWORD=mysecurepassword
    depends_on:
      - valkey


